version: "3.7"

services:
  appBuilder:
    image: node:lts-alpine
    networks:
      - ACI-vue
    volumes:
      - ./:/app
    working_dir: /app

  app:
    image: nginx:stable-alpine
    networks:
      - ACI-vue
    volumes:
      - ./:/usr/share/nginx/html:ro
    working_dir: /usr/share/nginx/html
    ports: 
      - 1001:80

networks:
  ACI-vue:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
