version: "3.3"

services:
  appBuilder:
    image: node:lts-alpine
    networks:
      - ACI-example
    volumes:
      - ./:/app
    working_dir: /app

  app:
    image: nginx:stable-alpine
    networks:
      - ACI-example
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    working_dir: /usr/share/nginx/html
    ports:
      - 1000:80

networks:
  ACI-example:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
