language: node_js
node_js:
- 10

services:
- docker

install:
- bash ./scripts/updateAll.sh

script:
- echo "."

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $PA_TOKEN
  local-dir: ./examples
  on:
    branch: develop # todo: put back to master
