language: minimal

services:
  - docker

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      name: Testing accessibility
      install:
        - docker-compose run --rm appBuilder npm ci
        - docker-compose run --rm appBuilder npm run build
        - docker-compose up -d app
      script:
        - docker-compose run --rm test

    - stage: deploy
      name: Deploy to github pages
      install:
        - docker-compose run --rm appBuilder npm ci
        - docker-compose run -e PUBLIC_URL="/accessibility-checker-infrastructure/" --rm appBuilder npm run build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $PA_TOKEN
        local-dir: ./dist/
