language: minimal

services:
- docker

install:
- bash ./scripts/updateAll.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $PA_TOKEN
  local-dir: ./examples/vanillajs
  on:
    branch: master
