language: minimal

services:
  - docker

install:
  - docker-compose -f `pwd`/example/docker-compose.yml run --rm appBuilder npm ci
  - docker-compose -f `pwd`/example/docker-compose.yml run --rm appBuilder npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $PA_TOKEN
  local-dir: ./example/dist/
  on:
    branch: develop
