language: php
php:
  - 7.3

services:
  - docker

install:
  - bash ./scripts/updateAll.sh

script:
  - bash ./scripts/startAll.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $PA_TOKEN
  local-dir: ./usr/share/nginx/html
  on:
    branch: develop # todo: change me to master
