version: "3.3"

services:
  appBuilder:
    image: node:lts-alpine
    networks:
      - ACI-example
    volumes:
      - ./example:/app
    working_dir: /app
    ports:
      - 1001:1001
    environment:
      - PUBLIC_URL=/

  app:
    image: nginx:stable-alpine
    networks:
      - ACI-example
    volumes:
      - ./example/dist:/usr/share/nginx/html:ro
    working_dir: /usr/share/nginx/html
    ports:
      - 1000:80

  test:
    image: enrise/puppeteer-cucumber:2.2
    networks:
      - ACI-example
    volumes:
      - ./tests/docker/features:/home/node/app/features

networks:
  ACI-example:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
